import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "스꾸딩 Cookbook",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        >
          <SidebarProvider>
            <ThemeProvider attribute="class" defaultTheme="light">
              <div className="flex flex-col min-h-screen">
                <main className="flex-grow">{children}</main> {/* ✅ flex-grow 추가 */}
                <footer className="border-t py-2 text-center text-sm text-muted mt-4">
                  © 2025 SKKUDING.
                </footer>
              </div>
            </ThemeProvider>
          </SidebarProvider>
        </body>
    </html>
  );
}
